# Generated by Django 5.0.7 on 2024-08-04 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('tipe_transaksi', models.CharField(choices=[('pemasukan', 'Pemasukan'), ('pengeluaran', 'Pengeluaran')], max_length=20)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deskripsi', models.TextField()),
                ('pengguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
